const data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
      genre_ids: [18, 80],
      id: 278,
      original_language: "en",
      original_title: "The Shawshank Redemption",
      overview:
        "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
      popularity: 177.714,
      poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
      release_date: "1994-09-23",
      title: "The Shawshank Redemption",
      video: false,
      vote_average: 8.709,
      vote_count: 27558,
    },
    {
      adult: false,
      backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      genre_ids: [18, 80],
      id: 238,
      original_language: "en",
      original_title: "The Godfather",
      overview:
        "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
      popularity: 200.396,
      poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      release_date: "1972-03-14",
      title: "The Godfather",
      video: false,
      vote_average: 8.689,
      vote_count: 20906,
    },
    {
      adult: false,
      backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
      genre_ids: [18, 80],
      id: 240,
      original_language: "en",
      original_title: "The Godfather Part II",
      overview:
        "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
      popularity: 114.637,
      poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
      release_date: "1974-12-20",
      title: "The Godfather Part II",
      video: false,
      vote_average: 8.571,
      vote_count: 12610,
    },
    {
      adult: false,
      backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
      genre_ids: [18, 36, 10752],
      id: 424,
      original_language: "en",
      original_title: "Schindler's List",
      overview:
        "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
      popularity: 128.02,
      poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
      release_date: "1993-12-15",
      title: "Schindler's List",
      video: false,
      vote_average: 8.568,
      vote_count: 16055,
    },
    {
      adult: false,
      backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
      genre_ids: [18],
      id: 389,
      original_language: "en",
      original_title: "12 Angry Men",
      overview:
        "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
      popularity: 64.94,
      poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
      release_date: "1957-04-10",
      title: "12 Angry Men",
      video: false,
      vote_average: 8.547,
      vote_count: 8809,
    },
    {
      adult: false,
      backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
      genre_ids: [16, 10751, 14],
      id: 129,
      original_language: "ja",
      original_title: "千と千尋の神隠し",
      overview:
        "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
      popularity: 110.701,
      poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
      release_date: "2001-07-20",
      title: "Spirited Away",
      video: false,
      vote_average: 8.537,
      vote_count: 16735,
    },
    {
      adult: false,
      backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
      genre_ids: [35, 18, 10749],
      id: 19404,
      original_language: "hi",
      original_title: "दिलवाले दुल्हनिया ले जायेंगे",
      overview:
        "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
      popularity: 36.319,
      poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
      release_date: "1995-10-20",
      title: "Dilwale Dulhania Le Jayenge",
      video: false,
      vote_average: 8.523,
      vote_count: 4452,
    },
    {
      adult: false,
      backdrop_path: "/plDp52MirFHc2PMJRMNWoG0kfr3.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      overview:
        "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
      popularity: 183.242,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.518,
      vote_count: 33256,
    },
    {
      adult: false,
      backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
      genre_ids: [14, 18, 80],
      id: 497,
      original_language: "en",
      original_title: "The Green Mile",
      overview:
        "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      popularity: 90.943,
      poster_path: "/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
      release_date: "1999-12-10",
      title: "The Green Mile",
      video: false,
      vote_average: 8.507,
      vote_count: 17690,
    },
    {
      adult: false,
      backdrop_path: "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      popularity: 113.918,
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      release_date: "2019-05-30",
      title: "Parasite",
      video: false,
      vote_average: 8.5,
      vote_count: 18531,
    },
    {
      adult: false,
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      genre_ids: [53, 80],
      id: 680,
      original_language: "en",
      original_title: "Pulp Fiction",
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      popularity: 175.724,
      poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
      release_date: "1994-09-10",
      title: "Pulp Fiction",
      video: false,
      vote_average: 8.488,
      vote_count: 28188,
    },
    {
      adult: false,
      backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
      genre_ids: [16, 10749, 18],
      id: 372058,
      original_language: "ja",
      original_title: "君の名は。",
      overview:
        "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
      popularity: 78.895,
      poster_path: "/vfJFJPepRKapMd5G2ro7klIRysq.jpg",
      release_date: "2016-08-26",
      title: "Your Name.",
      video: false,
      vote_average: 8.5,
      vote_count: 11522,
    },
    {
      adult: false,
      backdrop_path: "/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      overview:
        "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
      popularity: 180.188,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-17",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.483,
      vote_count: 24520,
    },
    {
      adult: false,
      backdrop_path: "/mzfx54nfDPTUXZOG48u4LaEheDy.jpg",
      genre_ids: [35, 18, 10749],
      id: 13,
      original_language: "en",
      original_title: "Forrest Gump",
      overview:
        "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
      popularity: 155.814,
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      release_date: "1994-06-23",
      title: "Forrest Gump",
      video: false,
      vote_average: 8.47,
      vote_count: 27723,
    },
    {
      adult: false,
      backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
      genre_ids: [37],
      id: 429,
      original_language: "it",
      original_title: "Il buono, il brutto, il cattivo",
      overview:
        "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
      popularity: 87.155,
      poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
      release_date: "1966-12-22",
      title: "The Good, the Bad and the Ugly",
      video: false,
      vote_average: 8.5,
      vote_count: 8744,
    },
    {
      adult: false,
      backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      overview:
        "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
      popularity: 42.154,
      poster_path: "/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.5,
      vote_count: 3759,
    },
    {
      adult: false,
      backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
      genre_ids: [18, 80],
      id: 769,
      original_language: "en",
      original_title: "GoodFellas",
      overview:
        "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
      popularity: 69.893,
      poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
      release_date: "1990-09-12",
      title: "GoodFellas",
      video: false,
      vote_average: 8.457,
      vote_count: 13036,
    },
    {
      adult: false,
      backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
      genre_ids: [16, 18, 10752],
      id: 12477,
      original_language: "ja",
      original_title: "火垂るの墓",
      overview:
        "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
      popularity: 0.076,
      poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
      release_date: "1988-04-16",
      title: "Grave of the Fireflies",
      video: false,
      vote_average: 8.5,
      vote_count: 5657,
    },
    {
      adult: false,
      backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
      genre_ids: [18, 10749],
      id: 11216,
      original_language: "it",
      original_title: "Nuovo Cinema Paradiso",
      overview:
        "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
      popularity: 36.063,
      poster_path: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
      release_date: "1988-11-17",
      title: "Cinema Paradiso",
      video: false,
      vote_average: 8.4,
      vote_count: 4422,
    },
    {
      adult: false,
      backdrop_path: "/gtlPLfpYRdswr4tCeJMxQefCyGo.jpg",
      genre_ids: [12, 18, 878],
      id: 157336,
      original_language: "en",
      original_title: "Interstellar",
      overview:
        "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
      popularity: 359.818,
      poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      release_date: "2014-11-05",
      title: "Interstellar",
      video: false,
      vote_average: 8.448,
      vote_count: 36208,
    },
  ],
  total_pages: 496,
  total_results: 9913,
};

const trendData = {
  page: 1,
  results: [
    {
      backdrop_path: "/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg",
      id: 426063,
      title: "Nosferatu",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 14, 27],
      popularity: 970.885,
      release_date: "2024-12-25",
      video: false,
      vote_average: 6.7,
      vote_count: 1264,
    },
    {
      backdrop_path: "/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg",
      id: 993710,
      title: "Back in Action",
      original_title: "Back in Action",
      overview:
        "Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.",
      poster_path: "/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35],
      popularity: 1626.554,
      release_date: "2025-01-15",
      video: false,
      vote_average: 6.7,
      vote_count: 390,
    },
    {
      backdrop_path: "/b85bJfrTOSJ7M5Ox0yp4lxIxdG1.jpg",
      id: 939243,
      title: "Sonic the Hedgehog 3",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 35, 10751],
      popularity: 4984.588,
      release_date: "2024-12-19",
      video: false,
      vote_average: 7.7,
      vote_count: 806,
    },
    {
      backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      id: 402431,
      title: "Wicked",
      original_title: "Wicked",
      overview:
        "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      poster_path: "/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10749, 14],
      popularity: 962.586,
      release_date: "2024-11-20",
      video: false,
      vote_average: 7,
      vote_count: 1422,
    },
    {
      backdrop_path: "/v9Du2HC3hlknAvGlWhquRbeifwW.jpg",
      id: 539972,
      title: "Kraven the Hunter",
      original_title: "Kraven the Hunter",
      overview:
        "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      poster_path: "/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12, 14, 53],
      popularity: 4138.501,
      release_date: "2024-12-11",
      video: false,
      vote_average: 6.549,
      vote_count: 726,
    },
    {
      backdrop_path: "/zGLQmrmIB56kMZPnzqReIOBay1B.jpg",
      id: 507241,
      title: "The Killer's Game",
      original_title: "The Killer's Game",
      overview:
        "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.",
      poster_path: "/4bKlTeOUr5AKrLky8mwWvlQqyVd.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 80],
      popularity: 92.386,
      release_date: "2024-09-12",
      video: false,
      vote_average: 6.8,
      vote_count: 181,
    },
    {
      backdrop_path: "/pQesMch1KeIfpCwoZfMPTZDR5Gd.jpg",
      id: 933260,
      title: "The Substance",
      original_title: "The Substance",
      overview:
        "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
      poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 749.004,
      release_date: "2024-09-07",
      video: false,
      vote_average: 7.1,
      vote_count: 3365,
    },
    {
      backdrop_path: "/wwARk7hRIfHfh2n2ubN6N7lvTne.jpg",
      id: 710295,
      title: "Wolf Man",
      original_title: "Wolf Man",
      overview:
        "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
      poster_path: "/tUtuMtC6oaRXr4x2B5Xi6ABdMCv.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 327.557,
      release_date: "2025-01-15",
      video: false,
      vote_average: 6.757,
      vote_count: 72,
    },
    {
      backdrop_path: "/m8iL42J8CuXh745BaQBa6b1mNrP.jpg",
      id: 1101448,
      title: "Unstoppable",
      original_title: "Unstoppable",
      overview:
        "Unstoppable is the inspiring true story of Anthony Robles who was born with one leg but whose unbreakable resolve empowered him to defy the odds and pursue his dreams. With the unwavering love and support of his devoted mother and the encouragement of his coaches, Anthony fights through adversity to earn a spot on the Arizona State Wrestling team on his quest to become an NCAA Champion.",
      poster_path: "/xanYKxuFkDPrMngvm1NSHVGOEjS.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 36],
      popularity: 156.653,
      release_date: "2024-12-06",
      video: false,
      vote_average: 4,
      vote_count: 66,
    },
    {
      backdrop_path: "/haX32ZQxOgDWcJO5sTiTUEE1Ulr.jpg",
      id: 1388694,
      title: "The Calendar Killer",
      original_title: "Sebastian Fitzeks Der Heimweg",
      overview: "",
      poster_path: "/bnciRmZZSdyqp7HcrAwNG0mObaP.jpg",
      media_type: "movie",
      adult: false,
      original_language: "de",
      genre_ids: [80, 53],
      popularity: 345.852,
      release_date: "2025-01-15",
      video: false,
      vote_average: 6.3,
      vote_count: 81,
    },
    {
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      id: 1249289,
      title: "Alarum",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 80, 53],
      popularity: 451.569,
      release_date: "2025-01-16",
      video: false,
      vote_average: 5.6,
      vote_count: 31,
    },
    {
      backdrop_path: "/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg",
      id: 1013850,
      title: "A Real Pain",
      original_title: "A Real Pain",
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      poster_path: "/yaTFjMNh8D78dDHrglivOTv5YOx.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 18],
      popularity: 254.883,
      release_date: "2024-11-01",
      video: false,
      vote_average: 6.8,
      vote_count: 245,
    },
    {
      backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
      id: 762509,
      title: "Mufasa: The Lion King",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      poster_path: "/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 16],
      popularity: 2196.48,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.43,
      vote_count: 820,
    },
    {
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 1402.076,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.8,
      vote_count: 2508,
    },
    {
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      id: 823219,
      title: "Flow",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      media_type: "movie",
      adult: false,
      original_language: "lv",
      genre_ids: [16, 14, 12],
      popularity: 520.353,
      release_date: "2024-08-29",
      video: false,
      vote_average: 8.4,
      vote_count: 852,
    },
    {
      backdrop_path: "/hmZnqijPaaACjenDkrbWcCmcADI.jpg",
      id: 549509,
      title: "The Brutalist",
      original_title: "The Brutalist",
      overview:
        "Escaping post-war Europe, visionary architect László Tóth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
      poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18],
      popularity: 122.113,
      release_date: "2024-12-20",
      video: false,
      vote_average: 6.1,
      vote_count: 38,
    },
    {
      backdrop_path: "/2P0PUkQ1tNHNYTEmtbBmM8MfXBG.jpg",
      id: 696506,
      title: "Mickey 17",
      original_title: "Mickey 17",
      overview:
        "Mickey Barnes has found himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.",
      poster_path: "/sY4n1osXuddwZokEmWUu1kq7U8g.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 28, 35],
      popularity: 72.411,
      release_date: "2025-02-28",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
      id: 558449,
      title: "Gladiator II",
      original_title: "Gladiator II",
      overview:
        "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
      poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 18],
      popularity: 1278.402,
      release_date: "2024-11-05",
      video: false,
      vote_average: 6.8,
      vote_count: 2449,
    },
    {
      backdrop_path: "/2ERLqcEBaJCIpBVR9O7RAapMGrw.jpg",
      id: 1059128,
      title: "Queer",
      original_title: "Queer",
      overview:
        "1950. William Lee, an American expat in Mexico City, spends his days almost entirely alone, except for a few contacts with other members of the small American community. His encounter with Eugene Allerton, an expat former soldier, new to the city, shows him, for the first time, that it might be finally possible to establish an intimate connection with somebody.",
      poster_path: "/xe4b2TMciLKA1C0JlhWxb4ENLln.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10749],
      popularity: 261.29,
      release_date: "2024-11-27",
      video: false,
      vote_average: 7.3,
      vote_count: 116,
    },
    {
      backdrop_path: "/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg",
      id: 1064213,
      title: "Anora",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10749, 35, 18],
      popularity: 353.763,
      release_date: "2024-10-14",
      video: false,
      vote_average: 7,
      vote_count: 775,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

const upcommingData = {
  dates: {
    maximum: "2025-02-19",
    minimum: "2025-01-29",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg",
      genre_ids: [18, 14, 27],
      id: 426063,
      original_language: "en",
      original_title: "Nosferatu",
      overview:
        "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      popularity: 970.885,
      poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      release_date: "2024-12-25",
      title: "Nosferatu",
      video: false,
      vote_average: 6.7,
      vote_count: 1264,
    },
    {
      adult: false,
      backdrop_path: "/fzjH7kt1017R9EckLDmWmH5pGhD.jpg",
      genre_ids: [28, 27, 53],
      id: 970450,
      original_language: "en",
      original_title: "Werewolves",
      overview:
        "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
      popularity: 929.507,
      poster_path: "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
      release_date: "2024-12-04",
      title: "Werewolves",
      video: false,
      vote_average: 6.397,
      vote_count: 219,
    },
    {
      adult: false,
      backdrop_path: "/i3CAo9UMGsvlU9k3Svd63rRDeZx.jpg",
      genre_ids: [16, 18, 35],
      id: 1064486,
      original_language: "en",
      original_title: "Memoir of a Snail",
      overview:
        "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
      popularity: 777.145,
      poster_path: "/lWh5OlerPR1c1cfn1ZLq0lpqFds.jpg",
      release_date: "2024-10-17",
      title: "Memoir of a Snail",
      video: false,
      vote_average: 7.8,
      vote_count: 92,
    },
    {
      adult: false,
      backdrop_path: "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
      genre_ids: [16, 28, 878, 10751],
      id: 1184918,
      original_language: "en",
      original_title: "The Wild Robot",
      overview:
        "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
      popularity: 598.291,
      poster_path: "/9w0Vh9eizfBXrcomiaFWTIPdboo.jpg",
      release_date: "2024-09-12",
      title: "The Wild Robot",
      video: false,
      vote_average: 8.4,
      vote_count: 4055,
    },
    {
      adult: false,
      backdrop_path: "/7bIWKyWdT04HTY3PqLETT8CH7jo.jpg",
      genre_ids: [28, 80, 53],
      id: 974453,
      original_language: "en",
      original_title: "Absolution",
      overview:
        "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      popularity: 488.512,
      poster_path: "/2MeQG5Vq8rUnRAa463BZe5GNhVk.jpg",
      release_date: "2024-10-31",
      title: "Absolution",
      video: false,
      vote_average: 5.8,
      vote_count: 276,
    },
    {
      adult: false,
      backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      genre_ids: [16, 14, 12],
      id: 823219,
      original_language: "lv",
      original_title: "Straume",
      overview:
        "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      popularity: 520.353,
      poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      release_date: "2024-08-29",
      title: "Flow",
      video: false,
      vote_average: 8.4,
      vote_count: 852,
    },
    {
      adult: false,
      backdrop_path: "/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg",
      genre_ids: [10749, 35, 18],
      id: 1064213,
      original_language: "en",
      original_title: "Anora",
      overview:
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
      popularity: 353.763,
      poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
      release_date: "2024-10-14",
      title: "Anora",
      video: false,
      vote_average: 7,
      vote_count: 775,
    },
    {
      adult: false,
      backdrop_path: "/qSOMdbZ6AOdHR999HWwVAh6ALFI.jpg",
      genre_ids: [28, 80, 53],
      id: 1249289,
      original_language: "en",
      original_title: "Alarum",
      overview:
        "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
      popularity: 451.569,
      poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
      release_date: "2025-01-16",
      title: "Alarum",
      video: false,
      vote_average: 5.6,
      vote_count: 31,
    },
    {
      adult: false,
      backdrop_path: "/q3Rgy4pQlPBou8ilYaVdHmjylyV.jpg",
      genre_ids: [28, 80, 53],
      id: 604685,
      original_language: "en",
      original_title: "Den of Thieves 2: Pantera",
      overview:
        "Big Nick is back on the hunt in Europe and closing in on Donnie, who is embroiled in the treacherous and unpredictable world of diamond thieves and the infamous Panther mafia, as they plot a massive heist of the world's largest diamond exchange.",
      popularity: 301.371,
      poster_path: "/scZfHuvRwUKZMbZauWMvjEX5g6N.jpg",
      release_date: "2025-01-08",
      title: "Den of Thieves 2: Pantera",
      video: false,
      vote_average: 6.7,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: "/9s9o9RT9Yj6nDuRJjnJm78WFoFl.jpg",
      genre_ids: [28, 27, 53, 878],
      id: 1051896,
      original_language: "en",
      original_title: "Arcadian",
      overview:
        "In the near future, on a decimated Earth, Paul and his twin sons face terror at night when ferocious creatures awaken. When Paul is nearly killed, the boys come up with a plan for survival, using everything their father taught them to keep him alive.",
      popularity: 273.77,
      poster_path: "/spWV1eRzlDxvai8LbxwAWR0Vst4.jpg",
      release_date: "2024-04-12",
      title: "Arcadian",
      video: false,
      vote_average: 6.1,
      vote_count: 564,
    },
    {
      adult: false,
      backdrop_path: "/fViElUGfdoZjtnVxvSpJX8TwxY6.jpg",
      genre_ids: [35, 18],
      id: 1013850,
      original_language: "en",
      original_title: "A Real Pain",
      overview:
        "Mismatched cousins David and Benji reunite for a tour through Poland to honor their beloved grandmother. The adventure takes a turn when the pair's old tensions resurface against the backdrop of their family history.",
      popularity: 254.883,
      poster_path: "/yaTFjMNh8D78dDHrglivOTv5YOx.jpg",
      release_date: "2024-11-01",
      title: "A Real Pain",
      video: false,
      vote_average: 6.8,
      vote_count: 245,
    },
    {
      adult: false,
      backdrop_path: "/2wqYNWasS3cxjAvoNfUTAZ58XGT.jpg",
      genre_ids: [18],
      id: 1088514,
      original_language: "es",
      original_title: "La habitación de al lado",
      overview:
        "Ingrid and Martha were close friends in their youth, when they worked together at the same magazine. Ingrid went on to become an autofiction novelist while Martha became a war reporter, and they were separated by the circumstances of life. After years of being out of touch, they meet again in an extreme but strangely sweet situation.",
      popularity: 255.048,
      poster_path: "/786Uu8eHfctp2TkII7ga1AnTBSs.jpg",
      release_date: "2024-10-07",
      title: "The Room Next Door",
      video: false,
      vote_average: 7.013,
      vote_count: 268,
    },
    {
      adult: false,
      backdrop_path: "/2ERLqcEBaJCIpBVR9O7RAapMGrw.jpg",
      genre_ids: [18, 10749],
      id: 1059128,
      original_language: "en",
      original_title: "Queer",
      overview:
        "1950. William Lee, an American expat in Mexico City, spends his days almost entirely alone, except for a few contacts with other members of the small American community. His encounter with Eugene Allerton, an expat former soldier, new to the city, shows him, for the first time, that it might be finally possible to establish an intimate connection with somebody.",
      popularity: 261.29,
      poster_path: "/xe4b2TMciLKA1C0JlhWxb4ENLln.jpg",
      release_date: "2024-11-27",
      title: "Queer",
      video: false,
      vote_average: 7.3,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: "/a3PBAmXUXuazAzr83WNzRaBS33I.jpg",
      genre_ids: [27, 53],
      id: 978796,
      original_language: "en",
      original_title: "Bagman",
      overview:
        "For centuries and across cultures, parents have warned their children of the legendary Bagman, who snatches innocent children and stuffs them into his vile, rotting bag—never to be seen again. Patrick McKee narrowly escaped such an encounter as a boy, which left him with lasting scars throughout his adulthood. Now, Patrick’s childhood tormentor has returned, threatening the safety of his wife Karina and son Jake.",
      popularity: 228.429,
      poster_path: "/53IK9rlZJbwFYbNnJZiLq7UWxkT.jpg",
      release_date: "2024-09-20",
      title: "Bagman",
      video: false,
      vote_average: 6.292,
      vote_count: 171,
    },
    {
      adult: false,
      backdrop_path: "/bfh9Z3Ghz4FOJAfLOAhmc3ccnHU.jpg",
      genre_ids: [12, 14],
      id: 671,
      original_language: "en",
      original_title: "Harry Potter and the Philosopher's Stone",
      overview:
        "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
      popularity: 217.362,
      poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
      release_date: "2001-11-16",
      title: "Harry Potter and the Philosopher's Stone",
      video: false,
      vote_average: 7.906,
      vote_count: 27763,
    },
    {
      adult: false,
      backdrop_path: "/hctfNoMpQGfn3VXdBYb9p0P5bT5.jpg",
      genre_ids: [18],
      id: 1097549,
      original_language: "en",
      original_title: "Babygirl",
      overview:
        "A high-powered CEO puts her career and family on the line when she begins a torrid affair with her much younger intern.",
      popularity: 230.246,
      poster_path: "/A8HbTd0FemZyFCh5qvJFpHGiwF8.jpg",
      release_date: "2024-12-25",
      title: "Babygirl",
      video: false,
      vote_average: 5.7,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: "/jcEcle0wHoTpEkLmK4AcBKgWI45.jpg",
      genre_ids: [10749, 18],
      id: 1100099,
      original_language: "en",
      original_title: "We Live in Time",
      overview:
        "An up-and-coming chef and a recent divorcée find their lives forever changed when a chance encounter brings them together, in a decade-spanning, deeply moving romance.",
      popularity: 212.261,
      poster_path: "/oeDNBgnlGF6rnyX1P1K8Vl2f3lW.jpg",
      release_date: "2024-10-10",
      title: "We Live in Time",
      video: false,
      vote_average: 7.5,
      vote_count: 509,
    },
    {
      adult: false,
      backdrop_path: "/fyeyxFzZ3qYqDsaMVYF6sq3pp2n.jpg",
      genre_ids: [28, 12, 53],
      id: 1167271,
      original_language: "en",
      original_title: "Weekend in Taipei",
      overview:
        "A former DEA agent and a former undercover operative revisit their romance during a fateful weekend in Taipei, unaware of the dangerous consequences of their past.",
      popularity: 174.88,
      poster_path: "/qSc0AUvs8mRy00R9y8QYEHWIAQ9.jpg",
      release_date: "2024-09-19",
      title: "Weekend in Taipei",
      video: false,
      vote_average: 6.252,
      vote_count: 117,
    },
    {
      adult: false,
      backdrop_path: "/66nlC5LDZmDUWONGkUZT2BrOszG.jpg",
      genre_ids: [18],
      id: 974576,
      original_language: "en",
      original_title: "Conclave",
      overview:
        "After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.",
      popularity: 192.23,
      poster_path: "/m5x8D0bZ3eKqIVWZ5y7TnZ2oTVg.jpg",
      release_date: "2024-10-25",
      title: "Conclave",
      video: false,
      vote_average: 7.171,
      vote_count: 905,
    },
    {
      adult: false,
      backdrop_path: "/1LSMstNHwJnJD7tpnb8gZcgGNQR.jpg",
      genre_ids: [27, 53],
      id: 1164355,
      original_language: "id",
      original_title: "Lembayung",
      overview:
        "Arum and Pica, who wanted to complete their internship at Lembayung hospital, had to face mysterious terror from a woman satan who was suspected of hanged herself in the bathroom. The situation became even more tense after they asked others for help to the point where they threatened their own lives and those closest to them.",
      popularity: 195.795,
      poster_path: "/5x9LrW0yvtt6S3XovIQHgXfYvLL.jpg",
      release_date: "2024-09-19",
      title: "Lembayung",
      video: false,
      vote_average: 7.8,
      vote_count: 6,
    },
  ],
  total_pages: 41,
  total_results: 811,
};

export { trendData, upcommingData, data };
